ark:
  image: turzam/ark
  environment:
    SESSIONNAME: Ark Docker
    SERVERMAP: TheIsland
    SERVERPASSWORD: 
    ADMINPASSWORD: adminpassword
    BACKUPONSTART: 1
    UPDATEONSTART: 1
  volumes:
    - /my/path/to/ark:/ark
  ports:
   - 7778:7778/udp
   - 7778:7778
   - 27015:27015/udp
   - 27015:27015
   - 32330:32330
